const SOME_THING_WENT_WRONG = 'something went unexpected wrong'
const DELETED_SUCCESSFULLY = 'Deleted successfully'
const INTERNAL_SERVER_ERROR_CODE = 500
const SUCCESS_STATUS_CODE = 200

module.exports = {
    SOME_THING_WENT_WRONG,
    INTERNAL_SERVER_ERROR_CODE,
    DELETED_SUCCESSFULLY,
    SUCCESS_STATUS_CODE
}